### ISSUE TITLE
repl.it css bug

### ISSUE THREAD

**Issue by DabDatBass** [meower-scratch/openly#1]
that darn css bug is drivin' me crazy

**Comment by wgyt** [comment]
what css bug @DabDatBass

**Comment by thecoder876** [comment]
> what css bug @DabDatBass

@wgyt It's an ongoing issue with Repl.it that causes CSS styled pages to not work properly. I have some repl.co pages that don't work properly because of it.

**Comment by wgyt** [comment]
> > what css bug @DabDatBass
> 
> @wgyt It's an ongoing issue with Repl.it that causes CSS styled pages to not work properly. I have some repl.co pages that don't work properly because of it.

That hasn't ever happened on any of my repl.co pages, this might be an issue with our current css
